apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-argo-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: github.com/winsen1983-jpg/ArgoCDGitrepo

  sourceRepos:
    - https://github.com/winsen1983-jpg/ArgoCDGitrepo

  destinations:
    - namespace: k8s-argo-demo
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
